### ISSUE TITLE
DynamoDBItemWritable is not Serializable on 4.5.0 on Maven

### ISSUE THREAD

**Issue by boure** [awslabs/emr-dynamodb-connector#65]
DynamoDBItemWritable is not Serializable on 4.5.0 nor 4.4.0 **on Maven repository artifacts** (contradicting code on GitHub), but it is on 4.3.0.

Source: https://mvnrepository.com/artifact/com.amazon.emr/emr-dynamodb-hadoop

**Comment by taklwu** [comment]
it's weird that the code has java.io.Serializable for  [DynamoDBItemWritable](https://github.com/awslabs/emr-dynamodb-connector/blob/branch-4.5.0/emr-dynamodb-hadoop/src/main/java/org/apache/hadoop/dynamodb/DynamoDBItemWritable.java) but not the built artifacts, can you share us the stacktrace and how did you find that out? (can you share how to run a sample test program as well? )

**Comment by taklwu** [comment]
I downloaded the [public jar](http://central.maven.org/maven2/com/amazon/emr/emr-dynamodb-hadoop/4.5.0/emr-dynamodb-hadoop-4.5.0.jar) and opened that from intellij and [JD-GUI](http://jd.benow.ca/) and confirmed that the Serializable is missing, but when I checked out the branch-4.5.0 and checked the built jar under target directory, the jar has Serializable. 

I'm wondered how awslabs built the artifacts, and will update on this once we figured out what the problem is.

**Comment by mazenmelouk** [comment]
@taklwu so any updates about this issue?

**Comment by taklwu** [comment]
this has been investigated and PR #78  has provided a checksum for files to avoid having this issue again.
